### ISSUE TITLE
Missing `finetune.py` File Mentioned in `Makefile`

### ISSUE THREAD

**Issue by qqq202** [idea-iitd/NeuroCUT#2]
Hi,

I hope you are doing well. I am currently working with your repository and noticed that the `Makefile` in the `src` directory references a `finetune.py` script. However, I couldn't find this file in the repository or mentioned in the documentation.

Could you please provide some guidance on where I can find or how I can generate the finetune.py file? It would be very helpful for my current project.

Thank you in advance for your assistance!

Best regards,
qqq202

**Comment by rishi1001** [comment]
Hi,

Thank you for your interest in our work!

Initially, we used the `finetune.py` file, but it wasn’t included in the final repository since we didn’t rely on it for the final version. However, I’ve now added it to the `src` folder in case you’d like to use it for further fine-tuning.

**Comment by qqq202** [comment]
Thank you very much for your prompt response and for adding the finetune.py file to the repository! This will be very helpful for my ongoing work.
﻿
I really appreciate your support.
﻿
Best regards,
